'use strict';
const $=id=>document.getElementById(id), el=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=String(text);return node};
let config=null,snapshot=null,activePod=null,attentionOnly=false,auto=true,busy=false,queuedLoad=false,detectBusy=false,awsStatusBusy=false,requestId=0,detailRequest=0,logRequestId=0,namespaceTimer;
let logCaptureTimer=null,logCaptureRunning=false,logCaptureBusy=false,logLines=[],logSeen=new Set(),logSince='';
const LOCAL_TOKEN=document.querySelector('meta[name="local-token"]').content;
let currentView='eks',perfData=null,perfBusy=false,lastAutoKey='',azureDefinition=null,azureList=[],jtlText='';
const fmt=(value,digits=0)=>value==null?'—':new Intl.NumberFormat('es-CO',{maximumFractionDigits:digits}).format(value);
const query=data=>new URLSearchParams(data).toString();
const activeContext=()=> $('context').value==='@current'?(config?.current||''):$('context').value;
const selectedScope=()=>({context:activeContext(),namespace:$('namespace').value.trim()});
const sameScope=(a,b)=>a.context===b.context&&a.namespace===b.namespace;
async function api(path){let response;try{response=await fetch(path,{cache:'no-store'})}catch{throw Error('La aplicación local no está respondiendo. Vuelve a abrir EKS Console.')}const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw Error('La aplicación recibió una respuesta no válida. Intenta de nuevo.')}if(!response.ok)throw Error(data.error||'No fue posible consultar Kubernetes.');return data}
function badge(text,kind=''){const n=el('span','state '+kind);n.append(el('span','dot'),document.createTextNode(text));return n}
function connection(text,kind=''){const n=$('connectionState');n.className='status-chip '+kind;n.replaceChildren(el('span','dot'),el('span','',text));n.title=text+' · Revisar conexión AWS'}
function notify(text,error=false){$('notice').hidden=!text;$('notice').textContent=text;$('notice').className='notice'+(error?' error':'')}
function emptyRow(text){const tr=el('tr'),td=el('td','empty',text);td.colSpan=8;tr.append(td);$('rows').replaceChildren(tr)}
function clearView(text){snapshot=null;for(const id of ['total','ready','attention','restarts','cpu','memory','healthPercent','podCount'])$(id).textContent='—';$('healthRing').style.background='var(--line)';$('services').replaceChildren(el('span','muted small','Esperando una lectura del clúster.'));for(const id of ['cpuBar','memoryBar'])$(id).style.width='0';$('cpuCaption').textContent=$('memoryCaption').textContent='Sin métricas disponibles';$('updated').textContent='Sin lectura para este contexto';emptyRow(text)}
function filtered(){if(!snapshot)return[];const search=$('search').value.trim().toLowerCase(),micro=$('micro').value;return snapshot.pods.filter(p=>(!micro||p.micro===micro)&&(!attentionOnly||['danger','warning'].includes(p.severity))&&(!search||[p.name,p.micro,p.namespace,p.node,p.state].join(' ').toLowerCase().includes(search)))}
function resource(pods,key,limit,divisor,id){const measured=pods.filter(p=>p[key]!=null);$(id).textContent=measured.length?fmt(measured.reduce((n,p)=>n+p[key],0)/divisor,2):'—';const full=measured.length>0&&measured.every(p=>p[limit]>0);const capacity=full?measured.reduce((n,p)=>n+p[limit],0):0;const percent=capacity?measured.reduce((n,p)=>n+p[key],0)/capacity*100:null;$(id+'Caption').textContent=measured.length?`${measured.length}/${pods.length} pods con métricas`+(percent!=null?' · '+fmt(percent)+'% del límite':''):'Sin métricas disponibles';$(id+'Bar').style.width=percent==null?'0':Math.min(percent,100)+'%'}
function render(){if(!snapshot)return;const pods=filtered(),ready=pods.filter(p=>p.is_ready).length,issues=pods.filter(p=>['warning','danger'].includes(p.severity)).length;
$('total').textContent=pods.length;$('ready').textContent=ready;$('attention').textContent=issues;$('restarts').textContent=pods.reduce((n,p)=>n+p.restarts,0);$('scopeNote').textContent=new Set(pods.map(p=>p.micro)).size+' servicios · vista filtrada';$('attentionNote').textContent=issues?'Revisa los estados y eventos':'Sin alertas en esta lectura';$('podCount').textContent=pods.length;
const ratio=pods.length?ready/pods.length*100:0;$('healthPercent').textContent=pods.length?Math.round(ratio)+'%':'—';$('healthRing').style.background=`conic-gradient(var(--green) ${ratio}%, var(--line) 0)`;
const services=$('services');services.replaceChildren();const groups={};for(const p of pods){groups[p.micro]??={total:0,ready:0};groups[p.micro].total++;groups[p.micro].ready+=p.is_ready?1:0}for(const [name,s] of Object.entries(groups).slice(0,4)){const row=el('div','service-row'),title=el('div','row spread'),bar=el('div','bar'),fill=el('span');title.append(el('span','service-title',name),el('span','muted',s.ready+'/'+s.total));fill.style.width=(s.ready/s.total*100)+'%';bar.append(fill);row.append(title,bar);services.append(row)}if(!pods.length)services.append(el('span','muted small','Sin pods para estos filtros.'));if(Object.keys(groups).length>4)services.append(el('span','muted small','+'+(Object.keys(groups).length-4)+' servicios en la tabla'));
resource(pods,'cpu','cpu_limit',1000,'cpu');resource(pods,'memory','memory_limit',1024,'memory');
$('rows').replaceChildren();for(const p of pods){const tr=el('tr');const name=el('td'),button=el('button','pod-button',p.name);button.addEventListener('click',()=>openPod(p));name.append(button,el('div','pod-meta',p.micro+' · '+p.namespace));tr.append(name);const state=el('td');state.append(badge(p.state,p.severity));tr.append(state,el('td','',p.ready));for(const [key,lim,unit]of[['cpu','cpu_limit','m'],['memory','memory_limit',' MiB']]){const td=el('td','',p[key]==null?'—':fmt(p[key])+unit);if(p[key]!=null&&p[lim]>0){const bar=el('div','mini-bar'),fill=el('span');fill.style.width=Math.min(100,p[key]/p[lim]*100)+'%';bar.append(fill);td.append(bar)}tr.append(td)}tr.append(el('td','restart'+(p.restarts?' bad':''),p.restarts),el('td','muted',p.age));const go=el('td'),open=el('button','icon-button','›');open.setAttribute('aria-label','Ver '+p.name);open.style.border='0';open.addEventListener('click',()=>openPod(p));go.append(open);tr.append(go);$('rows').append(tr)}if(!pods.length)emptyRow('No se encontraron pods para estos filtros.');$('contextFoot').textContent=(snapshot.demo?'DEMO · ':'')+snapshot.context;
}
function microOptions(){const old=$('micro').value;$('micro').replaceChildren(new Option('Todos los servicios',''));for(const name of [...new Set(snapshot.pods.map(p=>p.micro))].sort())$('micro').append(new Option(name,name));if([...$('micro').options].some(o=>o.value===old))$('micro').value=old}
async function applyPodMetrics(promise,scope,id,podsMs){try{const data=await promise;if(id!==requestId||!snapshot||!sameScope(scope,selectedScope()))return;const values=new Map(data.metrics.map(m=>[m.namespace+'\0'+m.name,m]));for(const pod of snapshot.pods){const metric=values.get(pod.namespace+'\0'+pod.name);pod.cpu=metric?.cpu??null;pod.memory=metric?.memory??null}snapshot.metrics_error=data.error;render();$('updated').textContent=`Pods ${podsMs} ms · métricas ${data.query_ms} ms · ${new Date(snapshot.updated).toLocaleTimeString('es-CO')}`;notify(data.error?'Pods disponibles. CPU y memoria no están disponibles: '+data.error:'')}catch(e){if(id===requestId&&sameScope(scope,selectedScope()))notify('Pods disponibles. Las métricas no respondieron: '+e.message,true)}}
async function load(force=false){if(busy){queuedLoad=true;return false}const scope=selectedScope();if(!scope.context||!scope.namespace){clearView('Selecciona un contexto y un namespace exacto.');return false}if(scope.namespace==='*'){clearView('Las consultas globales están deshabilitadas. Escribe un namespace exacto.');notify('Por seguridad no se permite consultar todos los namespaces.',true);return false}const id=++requestId;busy=true;$('reload').disabled=true;const previous=snapshot;if(previous&&!sameScope(previous,scope))clearView('Consultando el contexto seleccionado...');connection('Consultando EKS');const metricsPromise=api('/api/pod-metrics?'+query(scope));try{const data=await api('/api/pods?'+query({...scope,metrics:false}));if(id!==requestId||!sameScope(scope,selectedScope()))return false;snapshot=data;microOptions();render();connection(data.demo?'Sesión de ejemplo':'EKS conectado',data.demo?'warning':'good');$('updated').textContent=`Pods ${data.query_ms} ms · cargando métricas…`;notify('');$('podPanel').classList.remove('stale');void applyPodMetrics(metricsPromise,scope,id,data.query_ms);return true}catch(e){void metricsPromise.catch(()=>{});if(id!==requestId||!sameScope(scope,selectedScope()))return false;connection('Conexión pendiente','danger');notify((snapshot?'No se pudo actualizar; se conserva la lectura anterior. ':'')+e.message,true);if(snapshot){$('updated').textContent='DATOS SIN ACTUALIZAR · Última lectura: '+new Date(snapshot.updated).toLocaleTimeString('es-CO');$('podPanel').classList.add('stale')}else clearView('Revisa tu sesión de AWS y el acceso al contexto seleccionado.');return false}finally{if(id===requestId){busy=false;$('reload').disabled=false}if(queuedLoad){queuedLoad=false;setTimeout(()=>load(true),0)}}}
function namespaceFor(context){try{return sessionStorage.getItem('namespace:'+context)||config.contexts.find(c=>c.name===context)?.namespace||'default'}catch{return config.contexts.find(c=>c.name===context)?.namespace||'default'}}
async function detect(initial=false,force=false){if(detectBusy)return false;detectBusy=true;const previous=activeContext(),selection=$('context').value;try{const c=await api('/api/config?'+query({refresh:force}));if(config){c.scripts=config.scripts||[];c.profiles=config.profiles||[]}config=c;$('demoBanner').hidden=!c.demo;$('context').replaceChildren(new Option('Automático · '+(c.contexts.find(x=>x.name===c.current)?.label||'sin contexto'),'@current'));for(const item of c.contexts)$('context').append(new Option((item.eks?'EKS · ':'')+item.label,item.name));$('context').value=c.contexts.some(x=>x.name===selection)?selection:'@current';if(initial||previous!==activeContext()||!$('namespace').value)$('namespace').value=namespaceFor(activeContext());connectionInfo();if(c.error){connection('Configuración pendiente','warning');notify(c.error,true);clearView('Abre Conexión AWS para revisar la configuración.');return false}if(!c.contexts.length){connection('Sin contexto EKS','warning');notify('No hay contextos en kubeconfig. Ejecuta tu conexión habitual y vuelve a detectar.');clearView('Esperando un contexto de Kubernetes.');return false}if(initial||previous!==activeContext()||!snapshot)return await load(true);return true}catch(e){connection('Aplicación sin conexión','danger');notify(e.message,true);return false}finally{detectBusy=false}}
function connectionInfo(){if(!config)return;const grid=$('connectionInfo');grid.replaceChildren();const context=activeContext(),temporary=(config.temporary_contexts||[]).includes(context);for(const[label,value]of[['kubectl',config.kubectl?'Disponible':'No encontrado'],['AWS CLI',config.aws?'Disponible':'No encontrado'],['Contextos',config.contexts.length+' detectados'],['Ruta activa',temporary?'Credenciales temporales':config.profile?'Perfil '+config.profile:'Sesión de kubeconfig']]){const tile=el('div','connection-tile');tile.append(el('strong','',label),el('p','',value));grid.append(tile)}const list=$('scriptList');list.replaceChildren();if(config.connected_script)list.append(el('p','instructions','La aplicación se inició mediante '+config.connected_script+'.'));for(const script of config.scripts){const box=el('div','script-item');box.append(el('strong','',script.name),el('p','',script.hints.join(' · ')),el('p','',script.path));list.append(box)}if(!config.scripts.length)list.append(el('p','instructions',config.demo?'La demostración no ejecuta scripts ni consulta AWS.':'No se detectaron scripts de conexión junto a la aplicación.'));$('launchCommand').textContent=config.scripts.length===1?'py pods_local.py --connect-script auto':'py pods_local.py --connect-script "C:\\ruta\\tu-script.ps1"'}
function setAwsStatus(data){const panel=$('awsStatusPanel'),connected=!!data?.connected;panel.className='connection-status '+(connected?'connected':data?.state==='checking'?'checking':'error');$('awsStatusTitle').textContent=connected?(data.source==='temporary'?'Credenciales temporales conectadas':data.source==='demo'?'Demostración activa':'Sesión local conectada'):(data?.state==='checking'?'Verificando sesión':'Conexión no verificada');$('awsStatusDetail').textContent=data?.message||'Revisa tu sesión y vuelve a intentar.';const identity=[data?.account&&'Cuenta '+data.account,data?.profile&&'Perfil '+data.profile,data?.context&&'Contexto '+data.context].filter(Boolean).join(' · ');$('awsIdentity').textContent=identity;$('awsIdentity').hidden=!identity}
async function refreshAwsStatus(){if(awsStatusBusy)return;const context=$('awsCredentialContext').value.trim()||activeContext();setAwsStatus({state:'checking',message:'Comprobando el contexto seleccionado…'});awsStatusBusy=true;$('verifyAws').disabled=true;try{const data=await api('/api/aws/status?'+query({context}));setAwsStatus(data);if(data.connected)connection(data.source==='demo'?'Sesión de ejemplo':'AWS y EKS conectados',data.source==='demo'?'warning':'good')}catch(e){setAwsStatus({state:'error',message:e.message})}finally{awsStatusBusy=false;$('verifyAws').disabled=false}}
async function loadConnectionDetails(){try{const details=await api('/api/config?details=true');if(!config)return;config={...config,profiles:details.profiles||[],scripts:details.scripts||[],connected_script:details.connected_script||config.connected_script};connectionInfo()}catch{}}
function openConnection(){connectionInfo();$('awsCredentialContext').value=activeContext();if(!$('connectionDialog').open)$('connectionDialog').showModal();void loadConnectionDetails();refreshAwsStatus()}
function openPod(p){resetLogCapture();activePod={...p,context:snapshot.context};$('podTitle').textContent=p.name;$('podSubtitle').textContent=p.namespace+' · '+snapshot.context;const detail=$('detailPane');detail.replaceChildren();const grid=el('dl','detail-grid');for(const[label,value]of[['Estado',p.state],['Contenedores listos',p.ready],['Nodo',p.node],['IP del pod',p.ip],['Creado',p.created?new Date(p.created).toLocaleString('es-CO'):'—'],['Reinicios',p.restarts]]){const group=el('div');group.append(el('dt','',label),el('dd','',value));grid.append(group)}detail.append(grid,el('h3','','Contenedores'));$('container').replaceChildren();for(const c of p.containers){$('container').append(new Option(c.name,c.name));const box=el('div','container-item'),head=el('div','row spread');head.append(el('strong','small',c.name),badge(c.ready?'Ready':'No listo',c.ready?'good':'warning'));box.append(head,el('p','',c.image));if(c.last_reason)box.append(el('p','','Última terminación: '+c.last_reason));box.append(el('pre','code',JSON.stringify(c.resources,null,2)));detail.append(box)}const failed=p.conditions.filter(c=>c.status==='False');if(failed.length){detail.append(el('h3','','Condiciones pendientes'));for(const c of failed)detail.append(el('p','instructions',c.type+' · '+(c.message||c.reason||'False')))}$('previous').checked=false;$('toggleLogCapture').disabled=false;activateTab('detail');$('podDialog').showModal()}
function activateTab(name){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));for(const tab of ['detail','logs','events'])$(tab+'Pane').hidden=tab!==name;if(name==='logs'&&!logLines.length)loadLogs();if(name==='events')loadEvents()}
function logTimestamp(line){const match=line.match(/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2}))/);return match?.[1]||''}
function copyToClipboard(text){const field=document.createElement('textarea');field.value=text;field.setAttribute('readonly','');field.setAttribute('aria-hidden','true');Object.assign(field.style,{position:'fixed',left:'-9999px',top:'0',opacity:'0'});document.body.append(field);field.select();field.setSelectionRange(0,field.value.length);let copied=false;try{copied=document.execCommand('copy')}finally{field.remove()}if(!copied)throw Error('El navegador bloqueó la copia. Selecciona el texto y usa Ctrl+C.')}
function renderLogStatus(text,kind=''){const bar=$('logCaptureStatus').parentElement;bar.className='log-statusbar'+(kind?' '+kind:'');$('logCaptureStatus').textContent=text;$('logLineCount').textContent=logLines.length+' '+(logLines.length===1?'línea':'líneas');$('copyLogs').disabled=!logLines.length;$('clearLogs').disabled=!logLines.length}
function appendLogText(text,replace=false){if(replace){logLines=[];logSeen.clear();logSince=''}for(const line of String(text||'').split(/\r?\n/)){if(!line||logSeen.has(line))continue;logSeen.add(line);logLines.push(line);const timestamp=logTimestamp(line);if(timestamp)logSince=timestamp}if(logLines.length>5000){logLines=logLines.slice(-5000);logSeen=new Set(logLines)}$('logs').textContent=logLines.join('\n');$('logs').scrollTop=$('logs').scrollHeight;renderLogStatus(logCaptureRunning?'Capturando en vivo · actualización cada 2,5 s':'Consulta actualizada',logCaptureRunning?'capturing':'')}
function stopLogCapture(message='Captura detenida'){logCaptureRunning=false;if(logCaptureTimer){clearTimeout(logCaptureTimer);logCaptureTimer=null}$('toggleLogCapture').textContent='Iniciar captura';$('toggleLogCapture').classList.remove('capturing');$('reloadLogs').disabled=false;renderLogStatus(message)}
function resetLogCapture(){stopLogCapture('Consulta puntual · en memoria · sin descargas');logRequestId++;logLines=[];logSeen.clear();logSince='';if($('logs'))$('logs').textContent='';if($('copyLogs'))$('copyLogs').disabled=true;if($('clearLogs'))$('clearLogs').disabled=true;if($('logCaptureStatus'))renderLogStatus('Consulta puntual · en memoria · sin descargas')}
function scheduleLogCapture(){if(!logCaptureRunning)return;logCaptureTimer=setTimeout(async()=>{await loadLogs({append:true});scheduleLogCapture()},2500)}
async function loadLogs({append=false}={}){if(!activePod)return;const id=++logRequestId,p=activePod,params={context:p.context,namespace:p.namespace,pod:p.name,container:$('container').value,previous:$('previous').checked};if(append&&logSince)params.since=logSince;logCaptureBusy=true;if(!append&&!logLines.length){$('logs').textContent='Consultando logs…';renderLogStatus('Consultando el contenedor…')}try{const data=await api('/api/logs?'+query(params));if(id!==logRequestId)return;appendLogText(data.text,!append)}catch(e){if(id===logRequestId){stopLogCapture('La captura se detuvo por un error');$('logs').textContent=logLines.length?logLines.join('\n'):e.message;renderLogStatus(e.message,'error')}}finally{if(id===logRequestId)logCaptureBusy=false}}
async function toggleLogCapture(){if(logCaptureRunning){stopLogCapture();return}if($('previous').checked){renderLogStatus('La captura continua está disponible para el contenedor actual.','error');return}logCaptureRunning=true;$('toggleLogCapture').textContent='Detener captura';$('toggleLogCapture').classList.add('capturing');$('reloadLogs').disabled=true;renderLogStatus('Iniciando captura en vivo…','capturing');if(!logLines.length)await loadLogs();if(logCaptureRunning)scheduleLogCapture()}
function clearLogs(){logLines=[];logSeen.clear();logSince=logCaptureRunning?new Date().toISOString():'';$('logs').textContent='';renderLogStatus(logCaptureRunning?'Captura activa · esperando nuevas líneas':'Logs limpiados',logCaptureRunning?'capturing':'')}
function copyLogs(){if(!logLines.length)return;try{copyToClipboard(logLines.join('\n'));renderLogStatus(logCaptureRunning?'Capturando en vivo · logs copiados':'Logs copiados al portapapeles',logCaptureRunning?'capturing':'')}catch(e){renderLogStatus(e.message,'error')}}
async function loadEvents(){if(!activePod)return;const id=++detailRequest,p=activePod;$('events').replaceChildren(el('p','muted small','Consultando eventos...'));try{const data=await api('/api/events?'+query({context:p.context,namespace:p.namespace,pod:p.name}));if(id!==detailRequest)return;$('events').replaceChildren();for(const e of data.events){const box=el('div','event');box.append(badge(e.type,e.type==='Warning'?'warning':'good'),el('strong','', ' '+e.reason),el('p','',e.message),el('small','',e.time+' · '+e.count+' ocurrencias'));$('events').append(box)}if(!data.events.length)$('events').append(el('p','muted small','No hay eventos disponibles para este pod.'))}catch(e){if(id===detailRequest)$('events').replaceChildren(el('p','instructions',e.message))}}
$('context').addEventListener('change',()=>{$('namespace').value=namespaceFor(activeContext());load(true)});$('namespace').addEventListener('input',()=>{clearTimeout(namespaceTimer);namespaceTimer=setTimeout(()=>{try{sessionStorage.setItem('namespace:'+activeContext(),$('namespace').value.trim())}catch{}load(true)},750)});$('namespace').addEventListener('keydown',e=>{if(e.key==='Enter'){clearTimeout(namespaceTimer);load(true)}});$('search').addEventListener('input',render);$('micro').addEventListener('change',render);$('reload').addEventListener('click',()=>load(true));$('allStates').onclick=()=>{attentionOnly=false;$('allStates').classList.add('active');$('problemStates').classList.remove('active');render()};$('problemStates').onclick=()=>{attentionOnly=true;$('problemStates').classList.add('active');$('allStates').classList.remove('active');render()};$('auto').onclick=()=>{auto=!auto;$('auto').textContent=auto?'● Actualización automática · 15 s':'Ⅱ Actualización pausada';if(auto)load()};$('theme').onclick=()=>{document.documentElement.classList.toggle('dark');try{localStorage.setItem('eks-theme',document.documentElement.classList.contains('dark')?'dark':'light')}catch{}};
$('connect').onclick=$('navConnection').onclick=$('connectionState').onclick=openConnection;$('navOverview').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('navPods').onclick=()=>{$('podPanel').scrollIntoView({behavior:'smooth'});$('search').focus({preventScroll:true})};$('detect').onclick=async()=>{const before=requestId,ready=await detect(false,true);if(ready&&requestId===before)await load(true);connectionInfo();await refreshAwsStatus()};$('verifyAws').onclick=refreshAwsStatus;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab));$('container').onchange=()=>{resetLogCapture();loadLogs()};$('previous').onchange=()=>{resetLogCapture();$('toggleLogCapture').disabled=$('previous').checked;loadLogs()};$('reloadLogs').onclick=()=>loadLogs();$('toggleLogCapture').onclick=toggleLogCapture;$('clearLogs').onclick=clearLogs;$('copyLogs').onclick=copyLogs;$('podDialog').addEventListener('close',()=>{detailRequest++;resetLogCapture();activePod=null});
try{if(localStorage.getItem('eks-theme')==='dark')document.documentElement.classList.add('dark')}catch{}setInterval(()=>{if(auto&&!document.hidden&&currentView==='eks')load()},15000);setInterval(()=>{if(!document.hidden&&!busy&&currentView==='eks')detect()},120000);
async function post(path,body){let response;try{response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':LOCAL_TOKEN},body:JSON.stringify(body)})}catch{throw Error('La aplicación local no está respondiendo. Vuelve a abrir EKS Console.')}const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw Error('La aplicación recibió una respuesta no válida. Intenta de nuevo.')}if(!response.ok)throw Error(data.error||'No se pudo completar la operación local.');return data}
function sectionNotice(id,text,error=false){$(id).hidden=!text;$(id).textContent=text;$(id).className='notice'+(error?' error':'')}
function azureSelection(){const kind=$('azKind').value;return {kind,definition_id:$('azId').value.trim(),stage:kind==='release'?$('azEnvironment').value:$('azStage').value.trim()}}
function showView(view){currentView=view;for(const name of ['eks','performance','inventory','azure'])$(name+'View').hidden=name!==view;const ids={eks:'navOverview',performance:'navPerformance',inventory:'navInventory',azure:'navAzure'};document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.id===ids[view]));if(view==='performance'){refreshPerformance();if(!perfData?.scope&&activeContext())setupPerformance('live')}if(view==='azure'&&config?.demo&&!azureList.length)loadAzureDefinitions();}
async function setupPerformance(mode){if(perfBusy)return;const target=selectedScope();if(!target.context||!target.namespace){sectionNotice('perfNotice','Selecciona contexto y namespace.',true);return}if(perfData&&(perfData.mode==='manual'||perfData.run?.active)&&mode!=='live'){sectionNotice('perfNotice','Finaliza la captura actual antes de iniciar una nueva.',true);showView('performance');return}if(mode==='auto'&&!azureSelection().definition_id){showView('azure');sectionNotice('azureNotice','Conecta Azure y elige el pipeline y ambiente que corresponden a este ámbito EKS.');return}perfBusy=true;try{perfData=await post('/api/performance/config',{...target,micro:$('micro').value,mode,selection:azureSelection()});jtlText='';renderPerformance();showView('performance')}catch(e){sectionNotice(currentView==='azure'?'azureNotice':'perfNotice',e.message,true)}finally{perfBusy=false}}
async function refreshPerformance(){try{perfData=await api('/api/performance');renderPerformance();if(perfData.mode==='auto'&&perfData.run?.active&&lastAutoKey!==perfData.run.key){lastAutoKey=perfData.run.key;showView('performance');}}catch(e){sectionNotice('perfNotice',e.message,true)}}
function svgEl(tag,attrs,text){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs||{}))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function drawChart(id,points,series,divisor=1,unit=''){const root=$(id);root.replaceChildren();if(!points.length){root.append(el('div','chart-empty','Las gráficas se construirán con las lecturas de esta sesión.'));return}const width=520,height=185,left=48,right=12,top=12,bottom=30,w=width-left-right,h=height-top-bottom;let max=0;for(const p of points)for(const s of series)if(p[s.key]!=null)max=Math.max(max,p[s.key]/divisor);max=max?max*1.12:1;const first=points[0].time,last=Math.max(points[points.length-1].time,first+15);const x=t=>left+(t-first)/(last-first)*w,y=v=>top+h-v/max*h;const svg=svgEl('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':id+' · '+unit});for(let i=0;i<4;i++){const value=max*i/3;svg.append(svgEl('line',{x1:left,y1:y(value),x2:width-right,y2:y(value),stroke:'var(--line)','stroke-width':1}));svg.append(svgEl('text',{x:left-7,y:y(value)+4,'text-anchor':'end',fill:'var(--muted)','font-size':10},fmt(value,1)))}svg.append(svgEl('text',{x:left,y:height-4,fill:'var(--muted)','font-size':9},new Date(first*1000).toLocaleTimeString('es-CO')));svg.append(svgEl('text',{x:width-right,y:height-4,'text-anchor':'end',fill:'var(--muted)','font-size':9},new Date(points[points.length-1].time*1000).toLocaleTimeString('es-CO')));for(const s of series){let d='',start=true,priorTime=null;for(const p of points){if(priorTime!==null&&p.time-priorTime>45)start=true;priorTime=p.time;if(p[s.key]==null){start=true;continue}d+=(start?'M':'L')+x(p.time).toFixed(1)+','+y(p[s.key]/divisor).toFixed(1)+' ';start=false}if(d)svg.append(svgEl('path',{d,fill:'none',stroke:s.color,'stroke-width':2.4,'stroke-dasharray':s.dash||'','stroke-linejoin':'round'}));if(points.length===1&&points[0][s.key]!=null)svg.append(svgEl('circle',{cx:x(first),cy:y(points[0][s.key]/divisor),r:3,fill:s.color}));}root.append(svg);const legend=el('div','chart-legend');for(const s of series){const label=el('span','',s.label);label.style.setProperty('--legend-color',s.color);legend.append(label)}root.append(legend)}
function renderPerformance(){if(!perfData)return;const d=perfData,latest=d.latest,samples=d.samples||[],sample=latest?.sample;let state=d.mode==='manual'?'Capturando':d.mode==='auto'?(d.run?.active?'Performance activo':d.ended?'Captura finalizada · en espera':'Esperando ejecución'):d.ended?'Captura finalizada':d.scope?'Observación en vivo':'Sin captura';$('perfState').textContent=state;$('perfState').className='status-chip '+(d.mode==='manual'||d.run?.active?'good':'');$('captureScope').textContent=d.scope?`${d.scope.context} · ${d.scope.namespace} · ${d.scope.micro||'Todos los servicios'}`:'Selecciona un ambiente de EKS.';$('startCapture').disabled=d.mode==='manual'||!!d.run?.active;$('stopCapture').disabled=!d.scope;
const issues=[d.error,d.azure_error,latest?.metrics_error].filter(Boolean);sectionNotice('perfNotice',issues.join(' · '),!!d.error);sectionNotice('runInfo',d.run?'Ejecución: '+d.run.name+' · '+d.run.status+(d.run.result?' · '+d.run.result:''):'');$('perfCpu').textContent=sample?.cpu!=null?fmt(sample.cpu/1000,2)+' cores':'—';$('perfMem').textContent=sample?.memory!=null?fmt(sample.memory/1024,2)+' GiB':'—';$('perfCpuMeta').textContent='Request '+fmt(sample?.cpu_request==null?null:sample.cpu_request/1000,2)+' · Limit '+fmt(sample?.cpu_limit==null?null:sample.cpu_limit/1000,2)+' cores';$('perfMemMeta').textContent='Request '+fmt(sample?.memory_request==null?null:sample.memory_request/1024,2)+' · Limit '+fmt(sample?.memory_limit==null?null:sample.memory_limit/1024,2)+' GiB';$('perfReady').textContent=sample?sample.ready+' / '+sample.total:'—';$('perfMeasured').textContent=sample?sample.measured+'/'+sample.total+' pods con CPU y memoria':'Sin métricas';$('perfSamples').textContent=samples.length;$('perfDuration').textContent=samples.length?fmt((samples[samples.length-1].time-samples[0].time)/60,1)+' min observados · cada 15 s':'Muestreo cada 15 s';
const cpuSeries=[{key:'cpu',label:'Uso observado',color:'#159b77'},{key:'cpu_request',label:'Requests',color:'#d5a700',dash:'5 4'},{key:'cpu_limit',label:'Limits',color:'#6983ac',dash:'3 4'}];drawChart('cpuChart',samples,cpuSeries,1000,'cores');drawChart('memChart',samples,cpuSeries.map(s=>({...s,key:s.key.replace('cpu','memory')})),1024,'GiB');drawChart('podsChart',samples,[{key:'total',label:'Pods observados',color:'#d5a700'},{key:'ready',label:'Ready',color:'#159b77'}],1,'pods');
$('hpaList').replaceChildren();const hpaAccess=latest?.access?.hpa;if(hpaAccess&&hpaAccess.status!=='available')$('hpaList').append(el('p','instructions','HPA: '+(hpaAccess.status==='forbidden'?'sin permiso de lectura':hpaAccess.message)));else if(latest&&!(latest.hpas||[]).length)$('hpaList').append(el('p','instructions','Sin HPA asociado por nombre en este ámbito. La etiqueta del microservicio puede diferir del Deployment; consulta todos los servicios para revisar.'));for(const h of latest?.hpas||[]){const box=el('div','hpa-item'),head=el('div','row spread');head.append(el('strong','',h.name),badge(`${h.current??'—'} / ${h.max??'—'}`,h.current>=h.max?'warning':'good'));const target=(h.targets||[]).map(t=>{const v=t.resource||t.containerResource||{};return v.name?`${v.name}: ${v.target?.averageUtilization!=null?v.target.averageUtilization+'% del request':v.target?.averageValue||'métrica'}`:t.type}).join(' · ');box.append(head,el('p','',`Mínimo ${h.min} · deseadas ${h.desired??'—'} · máximo ${h.max} · ${target}`));const bar=el('div','bar'),fill=el('span');fill.style.width=(h.max?Math.min(100,(h.current||0)/h.max*100):0)+'%';bar.append(fill);box.append(bar);$('hpaList').append(box)}
const rows=$('resourcesRows');rows.replaceChildren();for(const p of latest?.pods||[]){const tr=el('tr');tr.append(el('td','',p.name));for(const key of ['cpu','cpu_request','cpu_limit','memory','memory_request','memory_limit'])tr.append(el('td','',p[key]==null?'—':fmt(p[key])+(key.startsWith('cpu')?'m':' MiB')));rows.append(tr)}if(!latest){const tr=el('tr'),td=el('td','empty','Esperando la primera lectura...');td.colSpan=7;tr.append(td);rows.append(tr)}
$('findings').replaceChildren();for(const f of d.analysis||[]){const box=el('article','finding '+f.level);box.append(el('strong','',f.title),el('p','',f.evidence),el('p','action',f.action));$('findings').append(box)}$('coverageNote').textContent=d.coverage_note+' Las métricas faltantes se indican; el uso agregado puede ser parcial. Exporta el análisis antes de cerrar.';
$('jtlStats').hidden=!d.jtl;$('latencyChart').hidden=!d.jtl;if(d.jtl){const j=d.jtl;$('jtlStats').replaceChildren();for(const[label,value,note]of[['Muestras',fmt(j.samples),'Filas del archivo'],['P95',fmt(j.p95)+' ms','95% de las muestras'],['P99',fmt(j.p99)+' ms','99% de las muestras'],['Errores',fmt(j.error_percent,2)+'%',fmt(j.errors)+' muestras fallidas'],['Throughput',fmt(j.throughput,2)+'/s','Muestras por segundo']]){const card=el('div','jtl-stat');card.append(el('span','',label),el('strong','',value),el('span','',note));$('jtlStats').append(card)}$('jtlMessage').textContent=j.note;drawChart('latencyChart',j.series,[{key:'p95',label:'P95 por intervalo',color:'#6983ac'}],1,'ms')}
}
async function loadInventory(){const target=selectedScope();$('inventoryGrid').replaceChildren(el('p','muted','Consultando recursos accesibles...'));$('loadInventory').disabled=true;try{const data=await api('/api/inventory?'+query(target));$('inventoryGrid').replaceChildren();for(const r of data.resources){const card=el('article','inventory-card'),head=el('div','row spread');head.append(el('h3','',r.kind),badge(r.status==='available'?'Disponible':r.status==='forbidden'?'Sin permiso':'No disponible',r.status==='available'?'good':'warning'));card.append(head,el('strong','',r.count==null?'—':r.count));if(r.message)card.append(el('p','',r.message));if(r.names?.length)card.append(el('p','',r.names.join(' · ')));if(r.detail?.length){const details=el('details'),summary=el('summary','','Ver configuración');details.append(summary,el('pre','',JSON.stringify(r.detail,null,2)));card.append(details)}$('inventoryGrid').append(card)}sectionNotice('inventoryNotice',`${data.context||target.context} · ${data.namespace||target.namespace}`)}catch(e){sectionNotice('inventoryNotice',e.message,true)}finally{$('loadInventory').disabled=false}}
async function loadAzureDefinitions(){try{const data=await api('/api/azure/definitions');azureList=data.definitions||[];$('azDefinitions').replaceChildren(new Option('Seleccionar pipeline',''));for(const d of azureList)$('azDefinitions').append(new Option(d.kind+' · '+d.name,d.kind+':'+d.id));$('azureState').textContent=data.connected?(config?.demo?'Demo · datos simulados':'Conectado'):'Sin conexión';sectionNotice('azureNotice',(data.warnings||[]).join(' · '));}catch(e){sectionNotice('azureNotice',e.message,true)}}
async function connectAzure(e){e.preventDefault();$('azConnect').disabled=true;try{const authInfo=await post('/api/azure/connect',{organization:$('azOrg').value,project:$('azProject').value,auth:$('azAuth').value,token:$('azToken').value,block:$('azCredentialBlock').value});if(authInfo.organization)$('azOrg').value=authInfo.organization;if(authInfo.project)$('azProject').value=authInfo.project;if(authInfo.auth==='pat'){$('azAuth').value='pat';$('azAuth').dispatchEvent(new Event('change'))}$('azToken').value='';await loadAzureDefinitions();try{sessionStorage.setItem('az-project',JSON.stringify({org:$('azOrg').value,project:$('azProject').value}))}catch{}}catch(e){sectionNotice('azureNotice',e.message,true)}finally{$('azToken').value='';$('azCredentialBlock').value='';$('azConnect').disabled=false}}
async function readDefinition(){const {kind,definition_id}=azureSelection();if(!definition_id){sectionNotice('azureNotice','Escribe el ID de definición o selecciona un pipeline.');return}$('azReadDefinition').disabled=true;try{azureDefinition=await api('/api/azure/definition?'+query({kind,id:definition_id}));$('azEnvironment').replaceChildren(new Option('Selecciona el ambiente',''));for(const env of azureDefinition.environments)$('azEnvironment').append(new Option(env.name,env.id));renderVariables();sectionNotice('azureNotice',(azureDefinition.warnings||[]).join(' · '));}catch(e){sectionNotice('azureNotice',e.message,true)}finally{$('azReadDefinition').disabled=false}}
function renderVariables(){const filter=$('variableSearch').value.toLowerCase();const rows=(azureDefinition?.variables||[]).filter(v=>(v.name+' '+v.origin).toLowerCase().includes(filter));$('variableCount').textContent=rows.length;$('variablesRows').replaceChildren();for(const v of rows){const tr=el('tr');tr.append(el('td','',v.name),el('td','var-value',v.value),el('td','muted',v.origin));$('variablesRows').append(tr)}}
async function importJtl(){if(!jtlText){sectionNotice('perfNotice','Selecciona un archivo JTL/CSV primero.');return}try{perfData=await post('/api/performance/jtl',{csv:jtlText,label:$('jtlLabel').value,p95_ms:Number($('sloP95').value),errors_percent:Number($('sloErrors').value)});renderPerformance()}catch(e){sectionNotice('perfNotice',e.message,true)}}
function copyReport(){if(!perfData?.samples?.length&&!perfData?.jtl){sectionNotice('perfNotice','Primero captura métricas o importa los resultados.');return}const report={product:'Bancolombia EKS Console · propuesta local',copied_at:new Date().toISOString(),...perfData,azure_definition:azureDefinition};try{copyToClipboard(JSON.stringify(report,null,2));sectionNotice('perfNotice','Análisis copiado al portapapeles. No se creó ningún archivo.')}catch(e){sectionNotice('perfNotice',e.message,true)}}
function environments(){try{return JSON.parse(localStorage.getItem('eks-environments')||'[]')}catch{return[]}}
function renderEnvironments(){const list=environments(),old=$('environment').value;$('environment').replaceChildren(new Option('Sesión actual / personalizado',''));$('savedEnvironments').replaceChildren();for(const [i,v]of list.entries()){$('environment').append(new Option(v.name,String(i)));const row=el('div','script-item'),head=el('div','row spread'),del=el('button','small','Eliminar');del.onclick=()=>{const all=environments();all.splice(i,1);localStorage.setItem('eks-environments',JSON.stringify(all));renderEnvironments()};head.append(el('strong','',v.name),del);row.append(head,el('p','',v.context+' · '+v.namespace));$('savedEnvironments').append(row)}if([...$('environment').options].some(o=>o.value===old))$('environment').value=old}
function openEnvironments(){$('envContext').value=activeContext();$('envNamespace').value=$('namespace').value;renderEnvironments();$('environmentDialog').showModal()}
$('saveEnvironment').onclick=()=>{const v={name:$('envName').value.trim(),context:$('envContext').value.trim(),namespace:$('envNamespace').value.trim()};if(!v.name||!v.context||!v.namespace){$('envName').reportValidity();return}const list=environments(),index=list.findIndex(e=>e.name===v.name);if(index>=0)list[index]=v;else list.push(v);localStorage.setItem('eks-environments',JSON.stringify(list));renderEnvironments();$('environmentDialog').close()};$('environment').onchange=()=>{if($('environment').value==='')return;const v=environments()[Number($('environment').value)];if(!v)return;if(![...$('context').options].some(o=>o.value===v.context))$('context').append(new Option(v.context,v.context));$('context').value=v.context;$('namespace').value=v.namespace;load(true);};
$('navOverview').onclick=()=>showView('eks');$('navPods').onclick=()=>{showView('eks');$('podPanel').scrollIntoView({behavior:'smooth'})};$('navPerformance').onclick=()=>showView('performance');$('navInventory').onclick=()=>showView('inventory');$('navAzure').onclick=()=>showView('azure');$('manageEnvironments').onclick=openEnvironments;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('startCapture').onclick=()=>setupPerformance('manual');$('armCapture').onclick=$('azureArm').onclick=()=>setupPerformance('auto');$('stopCapture').onclick=async()=>{try{perfData=await post('/api/performance/finish',{});renderPerformance()}catch(e){sectionNotice('perfNotice',e.message,true)}};$('exportPerf').onclick=copyReport;$('loadInventory').onclick=loadInventory;$('azureForm').onsubmit=connectAzure;$('azAuth').onchange=()=>{$('patField').hidden=$('azAuth').value!=='pat';$('authHelp').textContent=$('azAuth').value==='pat'?'Introduce un PAT de lectura permitido por tu organización.':'Ejecuta az login en tu terminal para usar Microsoft Entra.'};$('azDisconnect').onclick=async()=>{await post('/api/azure/disconnect',{});azureDefinition=null;azureList=[];$('azureState').textContent='Sin conexión';$('azDefinitions').replaceChildren(new Option('Sin conexión',''));renderVariables()};$('azDefinitions').onchange=()=>{const v=$('azDefinitions').value;if(!v)return;const[kind,id]=v.split(':');$('azKind').value=kind;$('azId').value=id;readDefinition()};$('azReadDefinition').onclick=readDefinition;$('variableSearch').oninput=renderVariables;$('jtlFile').onchange=async()=>{const file=$('jtlFile').files[0];if(!file)return;if(file.size>10_000_000){sectionNotice('perfNotice','El archivo supera 10 MB.',true);return}jtlText=await file.text();await importJtl()};$('reprocessJtl').onclick=importJtl;
try{const p=JSON.parse(sessionStorage.getItem('az-project')||'null');if(p){$('azOrg').value=p.org;$('azProject').value=p.project}}catch{}renderEnvironments();setInterval(()=>{if(currentView==='performance'||perfData?.mode==='auto'||perfData?.mode==='manual')refreshPerformance()},5000);refreshPerformance();


$('toggleAwsSecret').onclick=()=>{const input=$('awsCredentialBlock'),masked=input.classList.toggle('masked');$('toggleAwsSecret').textContent=masked?'Mostrar':'Ocultar'};
$('applyAwsBlock').onclick=async()=>{const button=$('applyAwsBlock'),message=$('awsCredentialMessage'),context=$('awsCredentialContext').value.trim(),block=$('awsCredentialBlock').value.trim();message.className='credential-message';if(!context){message.textContent='Selecciona primero el contexto EKS.';message.classList.add('error');$('awsCredentialContext').focus();return}if(!block){message.textContent='Pega el bloque de credenciales temporales.';message.classList.add('error');$('awsCredentialBlock').focus();return}button.disabled=true;button.textContent='Validando con AWS…';message.textContent='Leyendo las variables y verificando la identidad con AWS.';message.classList.add('loading');try{const result=await post('/api/aws/session',{context,block});$('awsCredentialBlock').value='';setAwsStatus(result.status);message.className='credential-message good';message.textContent=result.demo?'Bloque válido en modo demostración.':'Conexión verificada. La consola ya usa estas credenciales para el contexto seleccionado.';const before=requestId;await detect();if(requestId===before)await load(true);connectionInfo()}catch(e){message.className='credential-message error';message.textContent=e.message;setAwsStatus({state:'error',message:e.message,context})}finally{button.disabled=false;button.textContent='Validar y conectar'}};
$('removeAwsBlock').onclick=async()=>{const button=$('removeAwsBlock'),message=$('awsCredentialMessage'),context=$('awsCredentialContext').value.trim();button.disabled=true;message.className='credential-message loading';message.textContent='Quitando las credenciales temporales…';try{const result=await post('/api/aws/disconnect',{context});$('awsCredentialBlock').value='';message.className='credential-message good';message.textContent='Credenciales temporales eliminadas. Se vuelve a usar la sesión local de AWS CLI.';setAwsStatus(result.status);await detect();connectionInfo()}catch(e){message.className='credential-message error';message.textContent=e.message}finally{button.disabled=false}};
$('connectionDialog').addEventListener('close',()=>{$('awsCredentialBlock').value='';$('awsCredentialBlock').classList.add('masked');$('toggleAwsSecret').textContent='Mostrar';$('awsCredentialMessage').textContent='';$('awsCredentialMessage').className='credential-message'});
detect(true);
